<?php
$this->headLink()->appendStylesheet($this->assetUrl('css/page-blocks.css', 'Omeka'));
$this->htmlElement('body')->appendAttribute('class', $pageBodyClass);
$this->pageTitle($page->title(), 2);
$nav = $site->publicNav();
$activePage = $nav->findActive($nav->getContainer());
switch ($this->siteSetting('subnav_display')) {
    case 'show';
        $displaySubnav = $this->displayNavigation;
        break;
    case 'hide':
        $displaySubnav = false;
        break;
    default:
        $displaySubnav = $this->displayNavigation && $activePage && $activePage['page']->hasPages();
}
$showPagePagination = $this->siteSetting('show_page_pagination', true);
?>

<?php if ($activePage): ?>
<?php if ($activePage['depth'] !== 0): ?>
<nav class="breadcrumbs"><?php echo $nav->breadcrumbs(); ?></nav>
<?php endif; ?>
<?php endif; ?>

<?php if ($activePage): ?>
<?php if ($displaySubnav): ?>
<nav class="sub-menu"><?php echo $nav->menu()->renderSubMenu(); ?></nav>
<?php endif; ?>
<?php endif; ?>

<?php $this->trigger('view.show.before'); ?>

<?php // Display site title as heading on welcome page only ?>
<?php if ($this->params()->fromRoute('page-slug') === 'welcome'): ?>
    <h1 style="text-align: center;"><?php echo $site->title(); ?></h1>
<?php endif; ?>

<div class="blocks">
    <?php echo $this->content; ?>
</div>
<?php $this->trigger('view.show.after'); ?>
<?php if ($showPagePagination): ?>
<?php echo $this->sitePagePagination(); ?>
<?php endif; ?>
